import requests
from datetime import datetime
import smtplib
import time
import keyboard

MY_LAT = "YourLatitude" # Replace with your latitude
MY_LONG = "YourLongitude" # Replace with your longitude
EMAIL = "YourEmail@gmail.com" # Replace with your Gmail email. Other emails will not work, since I used Gmail SMTP
PASSWORD = "YourPassword" # Replace with your Gmail password or the one generated by Gmail for use in app
start_time = time.time()

def main():
    """
    Sends an email notification if the ISS is overhead during sunset or sunrise hours.

    This function retrieves the current sunrise and sunset times for the specified latitude and longitude
    from the Sunrise-Sunset API. It then checks if the ISS is overhead and if the current time is within
    the sunset or sunrise hours. If both conditions are met, it sends an email notification using the Gmail SMTP
    server.

    Parameters:
    None

    Returns:
    None
    """
    
    parameters = {
    "lat": MY_LAT,
    "lng": MY_LONG,
    "formatted": 0,
    }

    response = requests.get("https://api.sunrise-sunset.org/json", params=parameters)
    response.raise_for_status()
    data = response.json()
    sunrise = int(data["results"]["sunrise"].split("T")[1].split(":")[0])
    sunset = int(data["results"]["sunset"].split("T")[1].split(":")[0])

    time_now = datetime.now().hour
    
    if is_iss_overhead() and time_now.hour >= sunset or time_now.hour <= sunrise:
        with smtplib.SMTP("smtp.gmail.com") as connection:
            connection.starttls()
            connection.login(user=EMAIL, password=PASSWORD)
            connection.sendmail(
                from_addr=EMAIL,
                to_addrs='andre.borja.miranda@gmail.com',
                msg=f"Subject:ISS OVERHEAD!\n\nLook up! The ISS is above you in the sky."
            )
            
def is_iss_overhead():
    response = requests.get(url="http://api.open-notify.org/iss-now.json")
    response.raise_for_status()
    data = response.json()

    iss_latitude = float(data["iss_position"]["latitude"])
    iss_longitude = float(data["iss_position"]["longitude"])
    
    return True if MY_LAT-5 <= iss_latitude <= MY_LAT+5 and MY_LONG-5 <= iss_longitude <= MY_LONG+5 else False #range() uses integers


# This keeps the code running in the background, but allows the user to press ctrl+alt+s to stop the program
while True:
    if time.time() - start_time >= 60:
        main()
        start_time = time.time()
    if keyboard.is_pressed('ctrl+alt+s'):
        print('Stopping program...')
        break
    time.sleep(0.1)